### ISSUE TITLE
question does not print the expected character

### ISSUE THREAD

**Issue by XNexusPrimeX** [anseki/readline-sync#100]
I want to use this character: "◊", but every time I put:
```js
const command = readlineSync.question('◊');
```
he returns
```
Ôùè
```

how do i return this character?

**Comment by anseki** [comment]
Hi @XNexusPrimeX, thank you for the comment.
You have to fix the character encoding such as UTF-8.
Are you using Windows?

**Comment by XNexusPrimeX** [comment]
> Oi @XNexusPrimeX, obrigado pelo comentário.
> Você tem que corrigir a codificação de caracteres, como UTF-8.
> Você está usando o Windows?

Yeah

**Comment by anseki** [comment]
This may help you: https://github.com/anseki/readline-sync/issues/48
Also, if you wrote the characters with hard coding, the file has to be saved with `utf8` encoding for `chcp 65001`.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
