### ISSUE TITLE
looking for help in building the console application with syntax highlight

### ISSUE THREAD

**Issue by dineshkumar02** [anseki/readline-sync#101]
Hi Team,

I am exploring this library, and unable to locate any example to do an inplace syntax highlight.

For example, consider a prompt, where user types some html/xml tags, which should be highlighted automatically.
I did this with readline library, by refreshing the line for each and every keystore. But, it's not seem to be effective, where every key store is refreshing the entire line and not giving a nice user experience.

Would someone help me here how to achieve the same with readline-sync.

Thanks in advance for your help.

Regards,
Dinesh

**Comment by anseki** [comment]
Hi @dineshkumar02, thank you for the comment.
Sorry, my English is poor.
What is the keystore?
Do you mean that you want to add colors in the terminal window?

**Comment by anseki** [comment]
Umm...
Sorry, I couldn't understand the topic.
Your example seems to be not using readlineSync. The `rl` has methods that I don't know.
Maybe, you are talking about "readline", not "readlineSync".
I am sorry that I could not be of any help to you.

**Comment by dineshkumar02** [comment]
Hi @anseki ,

I am sorry, let me put my question in this way.

By using readline-sync, shall we achieve the syntax color.
For example, in prompt user actually types the HTML code. Whenever he types the html code, we have to give the color.

Prompt> <html> </html>  ---This what user types in the prompt, and we have to give the syntax highlight instantly

Regards,
Dinesh Kumar

**Comment by anseki** [comment]
Do you mean that you want to add the syntax highlight (e.g. colors) before user pressing <kbd>Enter</kbd> key?

**Comment by dineshkumar02** [comment]
Yes @anseki,

Exactly, before pressing the enter we want to have the syntax highlight(colors).

**Comment by anseki** [comment]
You seem to be making TUI app. Then, you need TUI library, not CUI (CLI) library such as readlineSync.
In CUI (CLI), the "readline" reads a line via TTY. That is, the line is made by <kbd>Enter</kbd> key.
Therefore, readlineSync is not required for your app.
For example, Vim text editor that is very famous TUI app supports the syntax-highlight with TUI base library.

**Comment by dineshkumar02** [comment]
Thanks @anseki,

I will take your suggestions, and will look for the TUI libraries.

**Comment by anseki** [comment]
:smile:
