### ISSUE TITLE
Non-ASCII Character Issues

### ISSUE THREAD

**Issue by ciw1973** [anseki/readline-sync#102]
I have a simple piece of code which has five question prompts, and displays the responses, unchanged and as returned by the function, for the user to confirm; however non-ASCII characters entered at the prompt are getting changed by readline-sync:

![image](https://user-images.githubusercontent.com/2350088/107405273-0baca280-6aff-11eb-926a-a1c44f333315.png)

As the user entered text shows correctly, I don't believe this is due to a terminal encoding issue.

I'm running NodeJS v12.18.4, and executing the script in (Git)bash on Windows, but get exactly the same results when running it in Powershell and cmd.exe.

**Comment by anseki** [comment]
Hi @ciw1973, thank you for the comment.
In Windows, that may be a encoding issue even if the user entered text is correct, because Node.js uses UTF-8 as default.

**Comment by ciw1973** [comment]
Do you have any suggestions to either fix, or work around this?

This is pretty much the simplest possible case, and ideally it should work "out of the box".

**Comment by anseki** [comment]
This may help you: https://github.com/anseki/readline-sync/issues/48
Or, these are other information.
https://github.com/anseki/readline-sync/issues?q=is%3Aissue+chcp

**Comment by ciw1973** [comment]
I had looked through the previous issues before creating this ticket, however they all relate to issues with the text of the prompt (UTF-8 being displayed in the console) and my issue is with the user input.

I did try turning on "Beta: Use Unicode UTF-8 for worldwide language support" in Windows, but the result was the following:

![image](https://user-images.githubusercontent.com/2350088/107491379-f7aa8480-6b82-11eb-824d-e730f3faf73c.png)

**Comment by anseki** [comment]
For test, write the string data to a file with UTF-8 instead of printing on screen.
And check the file.

**Comment by ciw1973** [comment]
Writing the string returned by readline-sync directly to a file, and opening it in VS Code, shows the same issues as in my original post:

![image](https://user-images.githubusercontent.com/2350088/107495317-da2be980-6b87-11eb-80f1-ec3d24ba744b.png)

The hex for this is:

![image](https://user-images.githubusercontent.com/2350088/107495237-b9639400-6b87-11eb-8373-571df4f0dde9.png)

**Comment by anseki** [comment]
I see.
readlineSync just only receives string from user and output that, it does nothing to the string.
Therefore maybe you had better choose "Readline" that controls the encoding instead, or another module (e.g. [`prompts`](https://github.com/terkelg/prompts)).

**Comment by ciw1973** [comment]
OK, no worries.

**Comment by anseki** [comment]
:smile:
