### ISSUE TITLE
`hideEchoBack: true` disables backspace.

### ISSUE THREAD

**Issue by raklaptudirm** [anseki/readline-sync#104]
When input is requested using `readline_sync.question()` with `{ hideEchoBack: true }`, backspace doesn't work. So writing a wrong character can't be cleared.

For example (`|` is the cursor):
```
| 
```
`a` clicked.
```
*|
```
`<backspace>` clicked. (No changes)
```
*|
```

**Comment by anseki** [comment]
Hi @raklaptudirm, thank you for the comment.
Typically control keys (not only <kbd>Back Space</kbd>, <kbd>F1</kbd>, <kbd>DEL</kbd>, <kbd>ESC</kbd>, etc.) should be not accepted in CLI environment with hidden mode, and users also understand that.

**Comment by raklaptudirm** [comment]
Ok. Thanks for the confirmation.

**Comment by anseki** [comment]
:smile:
