### ISSUE TITLE
Is there any way to take multi-line input?

### ISSUE THREAD

**Issue by raklaptudirm** [anseki/readline-sync#105]
Is there any way to take multi-line input using `readline-sync`? If not, adding it will be really useful.

**Comment by raklaptudirm** [comment]
@anseki Thank you very much.

**Comment by raklaptudirm** [comment]
A thought: You should add this to the `README.md`

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
This method was already written in the README when it was implemented.

**Comment by raklaptudirm** [comment]
I was not talking about the method. You could add a  paragraph as to what to do if someone wants multiline input. Anyways thanks for the help.

**Comment by anseki** [comment]
I see.
The paragraph should not be added because the README is already explaining the multiple input, and also, many users are already using the method to input multiple lines.
Thank you for the suggestion.
