### ISSUE TITLE
Chinese character problem

### ISSUE THREAD

**Issue by tnnevol** [anseki/readline-sync#108]
already referenced issues https://github.com/anseki/readline-sync/issues/48
![image](https://user-images.githubusercontent.com/28475939/120594516-9f6dfa00-c473-11eb-8dc4-44d4bea6827f.png)
![image](https://user-images.githubusercontent.com/28475939/120594745-f70c6580-c473-11eb-9187-dcefbd0b9d26.png)
![image](https://user-images.githubusercontent.com/28475939/120594888-26bb6d80-c474-11eb-8373-8f0f3bd986f6.png)
system info
bersion	Windows 10 Professional
versionCode	20H2

**Comment by anseki** [comment]
Hi @tnnevol, thank you for the comment.
It seems that you did that in something that is not console (e.g. IDE such as VS Code).
If so, try that in console such as  Cmder, PowerShell, etc.

**Comment by tnnevol** [comment]
> Hi @tnnevol, thank you for the comment.
> It seems that you did that in something that is not console (e.g. IDE such as VS Code).
> If so, try that in console such as Cmder, PowerShell, etc.

This is the vscode editor. The terminal uses the Windows powershell. I just installed a terminal skin plugin（oh-my-posh），Even if you don't install it, it's garbled code

**Comment by anseki** [comment]
You misunderstood it maybe.
Please read this again: https://github.com/anseki/readline-sync/issues/48
As I said, that is a way to add fonts to Cmd.exe.

**Comment by tnnevol** [comment]
> You misunderstood it maybe.
> Please read this again: #48
> As I said, that is a way to add fonts to Cmd.exe.

The font of CMD has been changed and the character set is 65001. I'll show you again tomorrow

**Comment by anseki** [comment]
You misunderstood it again.
You changed the font of CMD, but you don't use CMD, you use VS Code.
If you want to use VS Code, you have to change font of VS Code, not CMD.

**Comment by tnnevol** [comment]
> You misunderstood it again.
> You changed the font of CMD, but you don't use CMD, you use VS Code.
> If you want to use VS Code, you have to change font of VS Code, not CMD.

After changing the font, both the windows CMD, PowerShell, vscode terminal and webstorm terminal are in the same situation. I'm very sorry that I'm using a translation tool, which may not express well.

**Comment by anseki** [comment]
Ok. :smile: 
So, could you close this issue if it was solved?

**Comment by tnnevol** [comment]
windows terminal PowerShell 
![image](https://user-images.githubusercontent.com/28475939/120732375-c978f800-c517-11eb-918d-da96343ed350.png)

windows CMD
![image](https://user-images.githubusercontent.com/28475939/120732409-d8f84100-c517-11eb-88cd-54c29b08489c.png)

windows PowerShell
![image](https://user-images.githubusercontent.com/28475939/120732459-edd4d480-c517-11eb-9217-4ec39eb40951.png)

my local environment can output chinese, but "readline-sync" always outputs garbled characters

**Comment by anseki** [comment]
You have to specify Unicode font.
Try to change the font.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by tnnevol** [comment]
我算是搞明白了，这老哥只想关闭问题，我一直以为是我的字体字符集不支持，后来我发现vue-cli的 vue create 从来没有乱码呀，然后我就换成了https://github.com/SBoudrias/Inquirer.js，真香

**Comment by anseki** [comment]
Thank you :smile:
