### ISSUE TITLE
Allow movements like in bash terminal (Left, Right)

### ISSUE THREAD

**Issue by riazufila** [anseki/readline-sync#109]
How do I move cursor left right without `^[[B^[[D^[[B^[[B^[[A^[[A` appearing?

**Comment by anseki** [comment]
Hi @riazufila, thank you for the comment.
Could you explain more?

**Comment by riazufila** [comment]
@anseki lets say i typed "Hello Wurld" as the answer for a prompt, I want to fix the typo, and the only way I could do so is by first using backspace instead of just traversing the cursor the left. Because when I try to press "Left" key, the cursor doesn't go to the left. Instead it outputs `^[[...` as I mentioned above.

**Comment by anseki** [comment]
I didn't read your code, but your code might have a bug.
With `question*` and `prompt*` methods, the moving cursor is enabled in almost environments.
For example:
```js
const readlineSync = require('readline-sync');
console.log(`You said "${readlineSync.question('INPUT: ')}".`);
```
Or, I don't know your environment, but that might be disabled by your environment.
https://github.com/anseki/readline-sync#control-characters

**Comment by riazufila** [comment]
Copy pasting just those two lines also produces the same result. I guess it is disabled by my environment. Thanks for your attention.

**Comment by anseki** [comment]
:smile:

**Comment by specious** [comment]
This is the same situation described in #22.

**Comment by anseki** [comment]
Hi @specious, thank you for the information. :smile:

**Comment by ShenQingchuan** [comment]
```bash
 › omz version
master (d4f5fa37)

› zsh --version
zsh --version
zsh 5.8 (x86_64-apple-darwin21.0)
```

OS: Mac OSX Monterery
Terminal Enviorment: iTerm2 (v3.4.12)

I can reproduce this problem, is there anyone could help ?

**Comment by anseki** [comment]
Hi @ShenQingchuan, thank you for the comment.
Did you try this example? : https://github.com/anseki/readline-sync/issues/109#issuecomment-915678808
