### ISSUE TITLE
Readline-sync not working in VSCode

### ISSUE THREAD

**Issue by PianoMan7** [anseki/readline-sync#111]
node.js version 16.13.1

readline-sync version 1.4.10

Microsoft Windows NT 10.0.19043.0 x64

Trying to run this simple code in VSCode:
------------------------------------------------
var readLine = require('readline-sync');

var name = readLine.question("What is your name? ")

console.log(Hey ${name}, you're a cool guy!)

Returns this error:
-----------------------
c:\ws\src\node_file.cc:1739: Assertion `(argc) == (5)' failed.
1: 00007FF62B5930AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
2: 00007FF62B522216 DSA_meth_get_flags+65542
3: 00007FF62B5225D1 DSA_meth_get_flags+66497
4: 00007FF62B516219 DSA_meth_get_flags+16393
5: 00007FF62BE0F5D6 v8::internal::Builtins::code_handle+172694
6: 00007FF62BE0F1C9 v8::internal::Builtins::code_handle+171657
7: 00007FF62BE0F48C v8::internal::Builtins::code_handle+172364
8: 00007FF62BE0F2F0 v8::internal::Builtins::code_handle+171952
9: 00007FF62BEE2641 v8::internal::SetupIsolateDelegate::SetupHeap+494673
10: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
11: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
12: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
13: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
14: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
15: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
16: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
17: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
18: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
19: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
20: 00007FF62BE74AEE v8::internal::SetupIsolateDelegate::SetupHeap+45310
21: 00007FF62BE72CFC v8::internal::SetupIsolateDelegate::SetupHeap+37644
22: 00007FF62BE728FB v8::internal::SetupIsolateDelegate::SetupHeap+36619
23: 00007FF62BD53641 v8::internal::Execution::CallWasm+1521
24: 00007FF62BD52F2F v8::internal::Execution::Call+191
25: 00007FF62BE35FCC v8::Function::Call+508
26: 00007FF62B5545CE node_api_get_module_file_name+3038
27: 00007FF62B558217 node::Start+983
28: 00007FF62B5585C8 node::Start+1928
29: 00007FF62B5BF009 node::LoadEnvironment+89
30: 00007FF62B4DAB83 cppgc::internal::NormalPageSpace::linear_allocation_buffer+53811
31: 00007FF62B557F1D node::Start+221
32: 00007FF62B3788CC RC4_options+348108
33: 00007FF62C3D3A88 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+14472
34: 00007FFFC96E7034 BaseThreadInitThunk+20
35: 00007FFFCAF62651 RtlUserThreadStart+33

This error occurs consistently when trying to run readline-sync.

**Comment by JunyuanChen** [comment]
This issue was originally reported to NodeJS at https://github.com/nodejs/node/issues/41223.

There have been similar issue reports before, #106 #92 .

This does not appear to be an issue with TTYs. Even if proper terminal emulators are used, it will still error out on Windows.
Furthermore, this should not trigger a v8 panic and crash the entire node process. https://github.com/nodejs/node/issues/41223#issuecomment-996861956 mentioned that the problem is caused by using `process.binding()`.

**Comment by anseki** [comment]
Hi @PianoMan7, @JunyuanChen, thank you for the comment.
As document says, readlineSync is a library to read/write via TTY.
Therefore, you have to use another library or a method for VS Code.

**Comment by JunyuanChen** [comment]
> readlineSync is a library to read/write via TTY. Therefore, you have to use another library or a method for VS Code.

The problem here is that apparently `process.binding('tty_wrap').TTY` node v16 on Windows crashes the entire node process when the returned object is used. Even with a proper terminal emulator (eg. mintty), it will still crash and dump a v8 (!) stack trace. This means that there is no way to try-catch since it is crashing v8.

In `lib/readline-sync.js`, there are statements like `if (IS_WIN)` so I assume this library does intend to support Windows?

**Comment by anseki** [comment]
@JunyuanChen, your issue seems to be different from this issue. That is an issue about redirection, it's not VS Code.
Anyway, you have to use another library because `fs.c` doesn't work now.

**Comment by ozanmuyes** [comment]
Adding `"console": "externalTerminal"` to `launch.json` works for me, like in the launch configuration below;

```json5
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "dev",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "console": "externalTerminal",
      "program": "${workspaceFolder}/index.js",
      "args": ["..."],
    }
  ]
}
```

**Comment by anseki** [comment]
Hi @ozanmuyes, thank you for the information. :smile:

**Comment by anseki** [comment]
Hi @lallumohan, thank you for the comment.
These may help you:
https://github.com/anseki/readline-sync/issues/90
https://github.com/anseki/readline-sync/issues/77
