### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by Gashmob** [anseki/readline-sync#113]
Hello :wave: 

With the function `keyInSelect` I can ask user to choose one option, but is there a method to do a multiple select?
Like this :
```
1. [ ] Lion
2. [x] Elephant
3. [x] Crocodile
4. [ ] Giraffe
5. [ ] Hippo

Which animals? [1...5] Press enter to continue...

You choose Elephant and Crocodile!
```

It can be very usefull for example if we need to choose return formats for an http request (it's my case)

(I open this issue as an idea for enhancement)

**Comment by anseki** [comment]
Hi @Gashmob, thank you for the comment.
You can call `keyInSelect` repeatedly and toggle the check state of specified item.
However, you seem to be making TUI app, then you need TUI library instead. CUI (CLI) library such as readlineSync is not required for your app.

**Comment by Gashmob** [comment]
Hi,
There is a check state for `keyInSelect` ? I didn't see that in the doc.
Otherwise, can you recommand me a TUI lib ?

**Comment by anseki** [comment]
readlineSync doesn't support the check state because that is not required for CLI, but that is very easy, it can be just a boolean variable.
Yes, I recommend you to use a TUI library instead.

**Comment by Gashmob** [comment]
Ok thanks !
Have you an idea of a tui lib i can use ?

**Comment by anseki** [comment]
Sorry, I can't choose one for your app because I don't know your app.
There are great libraries. :thumbsup:
