### ISSUE TITLE
Can't distinguish between EOD and a blank input line

### ISSUE THREAD

**Issue by unsaved** [anseki/readline-sync#114]
Please correct me if I'm missing something.

I want to just read stdin input lines like a traditional shell script.  I see that the readline-sync prompt loop gets "" (empty string) as `input` for both user entry (or piped data line) of empty string and for end-of-data.  So if I write a typical script that processes each input line until EOD, testing for `input === ""`, the program will accidentally terminate if the input happens to contain a blank line.  Is there any workaround for this other than dealing with the idiosyncracies of getRawInput.  (Turns me off of JavaScript that EOD determination takes so much effort whereas it's a non-issue for UNIX shell scripts, Perl, Java, C,...).

**Comment by anseki** [comment]
Hi @unsaved, thank you for the comment.
Is that related to the abandoned issues?
https://github.com/anseki/leader-line/issues/167
https://github.com/anseki/leader-line/issues/168

**Comment by unsaved** [comment]
No.  This Issue is designated for the readline-sync project not leader-line.
```
#!/usr/bin/env node

const readlineSync = require("readline-sync");

readlineSync.setDefaultOptions({prompt: ""});
readlineSync.promptLoop(input => {
    if (input === "") return true;  // Can not distinguish between closed stdin and "" input
    console.log(`Entered a ${typeof input}: <${input}>`);
});
```

**Comment by anseki** [comment]
Do you mean that you want to capture signal such as `Ctrl+D`?

**Comment by unsaved** [comment]
No.  I want your API to provide any synchronous way to distinguish blank line input vs. closed-input.  Whether that's by a special 'input' value or by a dedicated readline-sync function or some other means.

As it is, your API is inconsistent and misleading.  A callback 'input' param value of string "X" should mean that the input value was precisely "X".  As things are now, a callback 'input' param value of string "" means that the input value is either "" or that stdin was closed, and there is no way to distinguish which.

**Comment by anseki** [comment]
Sorry, I couldn't understand you. I think your plan is strange.
Almost typical CLI programs use the empty line or the signal (e.g. `Ctrl+D`) to get the EOD.
You don't like readlineSync and you don't need readlineSync maybe. You should use another library such as Readline (not readlineSync) instead.

**Comment by unsaved** [comment]
I guess that's what typical readline-sync users do.  I've been coding and using well over a thousand CLI scripts for many years, starting with Oracle installation and upgrade scripts.  Typical CLI C-shell and Bourne-shell scripts (inc. on Windows with MinGW/Cygwin/etc.) detect end of input with read simply returning false, "while read VAR; do...".  For Perl it's "while (<>) {...".  For Groovy, "while ((s = br.readLine()) != null) {".  Don't need to anything platform-specific in any of these languages.

Thanks for the recommendation for Readline.  I'll try that out.

**Comment by anseki** [comment]
Good luck :smile:

**Comment by unsaved** [comment]
readline module is purely asynchronous so isn't suitable for traditional shell scripting.

For posterity, in case somebody is looking for a synchronous read-line that
1. supports input of "" (blank line) not meaning "quit"
2. distinguishes end-of-input from "" (blank line)
3. supports piping stdin ("... | yourscript.js" or "yourscript.js < file.txt" or "yourscript <<< 'multi-line input')
... working solution at this time is module 'syncprompt'.  It's asynchronous prompt function returns "" for input of "" and JavaScript null for end-of-input, just like most scripting and development languages.

**Comment by anseki** [comment]
Thank you for the information :smile:
