### ISSUE TITLE
a qusetion about encoding

### ISSUE THREAD

**Issue by windkind88** [anseki/readline-sync#115]
Hello,developers, thank you very much for such a good project., It's my pleasure，however, there is a small problem in the process of using it,
```js
for(var i=1;i<=2;i++){
  var num = rdls.question('请输入第i个数:',{encoding:"utf8"} );
  console.log("输入的是"+num);
}
```
Running on win10 systems, Chinese will be garbled, on Linux will be displayed normally！
I hope to improve this problem, thank you very much！！！

**Comment by anseki** [comment]
Hi @windkind88, thank you for the comment.
The default value of the `encoding` is `'utf8'`. Therefore, Unicode (i.e. Chinese characters, etc.)  is supported. Note that you have to save the script file with "UTF-8" encoding.
Also, this may help you: https://github.com/anseki/readline-sync/issues/48

**Comment by windkind88** [comment]
> 嗨，@windkind88，感谢您的评论。的默认值为 。因此，支持统一码（即中文字符等）。请注意，您必须使用“UTF-8”编码保存脚本文件。另外，这可能会对您有所帮助： #48`encoding``'utf8'`

It has been solved. By changing CHCP 65001, the GBK garbled code problem has been solved. The code page of my previous Pshell is 936.

**Comment by anseki** [comment]
:smile: 
Could you close this issue if it was solved?

**Comment by windkind88** [comment]
> 😄如果解决了这个问题，你能关闭它吗？
好的，可能其他朋友也会遇到这个问题吧~

**Comment by windkind88** [comment]
> > 😄如果解决了这个问题，你能关闭它吗？

Well, maybe other friends have the same problem
