### ISSUE TITLE
backspace with hideEchoBack

### ISSUE THREAD

**Issue by fabpopa** [anseki/readline-sync#17]
Hi there,
When using `hideEchoBack`, such as  
```
var a = readlineSync.question("What's up?", { hideEchoBack: true });
```
the user can't press backspace to remove characters. Is this deliberately this way?
In Unix, you can typically delete characters when typing in a hidden password.

Thank you for the library and best wishes!

**Comment by anseki** [comment]
Hi fabpopa, Thank you for your post.
readlineSync deliberately ignore the backspace key, because:

1. Many CLI commands that hide input don't accept backspace key. I think that it should have the interface that is accustomed to use for many users.
2. Some platforms (and environments) don't support the readline-library that accept backspace key.
3. The shell in some platforms (and environments) doesn't support control characters that remove the shown characters.

The users that like GUI may want to edit hidden text, but I think that it is not big problem because there are many CLI commands that show nothing. (i.e. like `{mask: ''}`)
Then, some day, the situation may be changed.

**Comment by fabpopa** [comment]
All right, thanks!

**Comment by anseki** [comment]
Duplicate issue was moved from https://github.com/anseki/readline-sync/issues/35#issue-152772311
From @sant123

> Hi, according with these closed issues https://github.com/anseki/readline-sync/issues/27 https://github.com/anseki/readline-sync/issues/17 I'd say this issue persist, and maybe the explanation of the #17 is right, but if it does; why we would erase the normal content (not hidden) with the backspace key? And if we are planning to change a password, what happens if I make a mistake? Do I have to repeat the whole process? Take this as an example:
> * Please provide your current password: ******
> * Provide a new password: ****x** "I've made a mistake!, and then the program will accept this password as my new password"
> * Repeat your new password: ****x** "I have to do it in order to continue and then repeat the process"
> * Start over!
> 
> I think this module is really awesome because in some way, I remember the C#  ```Console.ReadLine() ``` I'll appreciate this issue gets solved.
> 
> Thanks.

**Comment by anseki** [comment]
Hi @sant123, thank you for your post.
readlineSync uses a hidden-input-interface that is provided by platform running it depending on the situation (e.g. bash in Linux-like, `ScriptPW.Password` in Windows-runtime, `InteropServices` in .NET Framework, etc.), and your platform may not support backspace key.
We have to handle a password very carefully, and many UIs are designed very strictly. Some UIs that are commonly used in CLI show nothing (even `*`), therefore backspace key will confuse user.
Then, typically UI requires user to input password twice because many users don't notice own mistake in hidden-input.
When the user mistook, UI requires the user to input it again.
[`questionNewPassword`](https://github.com/anseki/readline-sync#questionnewpassword) method may help you.
Hit only the Enter key if you want to retry from first one.

**Comment by sant123** [comment]
@anseki I'm on Windows 8.1. On the other hand, I haven't seen the last functionality of [```questionNewPassword```](https://github.com/anseki/readline-sync#questionnewpassword), now it looks like:

![image](https://cloud.githubusercontent.com/assets/7959437/15021841/8f555132-11ee-11e6-91b1-c65f9ddd633b.png)

It's a way to handle the issue. 

Thanks.

**Comment by anseki** [comment]
@sant123 Sorry, what is "last functionality" you said?
If it means that the user re-tries by pressing the Enter key, It seems that it worked fine, in your screen shot.

**Comment by sant123** [comment]
@anseki I'm sorry, it's "hadn't", I didn't notice about the mistake and the functionality, when I wrote this message I didn't test the questionNewPassword method.

**Comment by anseki** [comment]
:smiley: 
I'm glad that it helps you.

**Comment by maku** [comment]
@anseki Thank you for providing such a great library. (I really like it). But at this point I have to diasgree.

From a consumer point of view,  it would be fine to choose the appropriate behaviour. And I personally (and the users I write the app for) hate the behaviour when I am not able to use the backspace key .... So maybe it would be possible to provide a functionality to "override" the default behaviour?

**Comment by anseki** [comment]
Hi @maku, thank you for the comment.
I also think that, it may be better that readlineSync allows us to control the behavior with the backspace key.
But it has to work in many environments and situations (see: https://github.com/anseki/readline-sync/issues/17#issuecomment-216592684).
We have to handle a password carefully, and the UIs that are provided by the platform behave properly. Those might not support the backspace key.

**Comment by maku** [comment]
Hi @anseki, e.g. the way I use readline-sync is for in house tools. So the the environment is controlable. Furthermore it would be perfectly fine when the backspace is not available on some platforms (on most platforms it is)

**Comment by anseki** [comment]
Yes, you may be able to control the behavior if the environment is limited.
You can fork this repository and customize the code.
The control characters that contains the backspace-code are removed in this line:
https://github.com/anseki/readline-sync/blob/master/lib/readline-sync.js#L406
You have to use a version of Node.js and OS that support reading from TTY:
https://github.com/anseki/readline-sync/blob/master/lib/readline-sync.js#L256

**Comment by maku** [comment]
O.k. thank you - I understand this as the ultimative hint that this feature will it never make in the codebase :-) My users will have to live with this little flaw...

**Comment by anseki** [comment]
As I said in above, many CLIs that hide input don't accept backspace key. readlineSync should have the interface that is accustomed to use for many users. The backspace key will confuse users.
If your app users that like GUI may want the backspace key, you might have to choose TUI instead of CLI.

**Comment by maku** [comment]
@anseki no problem - but the simple point is (at least from my perspective), no offense, that it would be so easy to build in this functionality and to keep also the default behaviour as it is  (and to make some users happy, not only me). But of course it is no problem. I am glad you built such a great library. 
And when I feel this feature is a must then it would be possible to make a fork and change the behaviour (as you already mentioned) 

BTW, I don't know the abbreviation "TUI"  

Thank you for your effort!

**Comment by markostamcar** [comment]
@anseki, first of all, thank you for this library, it is wonderful! I am using it to provide a command prompt to a real DEC VT320 terminal at our Computer Museum in Slovenia.

I needed backspace to work with hideEchoBack, so I made a small change to `readline-sync.js` in function `_readlineSync`:
`      if (chunk) {
        if (chunk == "\x7f" && input.length > 0) {
          fs.writeSync(fdW, "\b\x1b[0K");
          input = input.slice(0, -1);
        }
        chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '');
      }`

And as a bonus, if you need the mask to be a string processing function, change this:

`            if (options.mask.includes("return")) {
              fs.writeSync(fdW, new Function("str", options.mask)(chunk));
            } else {
              fs.writeSync(fdW, (new Array(chunk.length + 1)).join(options.mask));
            }`

This way, you can set in options `mask: "return vt320(str)"` where `vt320` is a globally defined function (`global.vt320 = function vt320(str) { ...`

Hope this helps someone! :)

**Comment by anseki** [comment]
Hi @markostamcar, thank you for the information. :smile: 
That may help someone.

**Comment by rksdevs** [comment]
> @anseki, first of all, thank you for this library, it is wonderful! I am using it to provide a custom command prompt to a real DEC VT320 terminal at our Computer Museum in Slovenia.
> 
> ![VT320](https://raw.githubusercontent.com/markostamcar/muzej.si/master/vt320/vt320.jpg)
> 
> I needed backspace to work with hideEchoBack, so I made a small change to `readline-sync.js` in function `_readlineSync`:
> 
> ```
>       if (chunk) {
>         if (chunk == "\x7f" && input.length > 0) {
>           if (options.mask != '') { fs.writeSync(fdW, "\b\x1b[0K"); }
>           input = input.slice(0, -1);
>         }
>         chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '');
>       }
> ```
> 
> And as a bonus, if you need the mask to be a string processing function, change this:
> 
> ```
>             if (options.mask.includes("return")) {
>               fs.writeSync(fdW, new Function("str", options.mask)(chunk));
>             } else {
>               fs.writeSync(fdW, (new Array(chunk.length + 1)).join(options.mask));
>             }
> ```
> 
> This way, you can set in options `mask: "return vt320(str)"` where `vt320` is a globally defined function (`global.vt320 = function vt320(str) { ...`).
> 
> Hope this helps someone! :)
> 
> Edit: And if you want the cursor keys to recall the previous command (and suppress cursor key press codes on screen), do this:
> 
> ```
>         if (/\x1b\[[A-D]$/.test(rawInput) && options.mask != '') {
>           chunk = '';
>           fs.writeSync(fdW, (new Array(input.length + 1)).join("\b") + "\x1b[0K" + lastInput);
>           input = lastInput;
>         }
>         chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '');
> ```

Hello @markostamcar , I tried to update the _readlineSync function with your code snippet, but it is still not capturing backspace. I'm a novice programmer, working on a CLI app as a project so any help here would be highly appreciated!

**Comment by markostamcar** [comment]
@rksdevs, I'm happy to help. **Please be sure to give more information next time, such as OS, Node version and readlineSync code snippet from your actual app as well as the patched readline-sync.js!**

Here is a working patch I just tested and confirmed it works:

```diff
      if (chunk && typeof (line = (chunk.match(/^(.*?)[\r\n]/) || [])[1]) === 'string') {
        chunk = line;
        atEol = true;
      }

      // other ctrl-chars
      // eslint-disable-next-line no-control-regex
-       if (chunk) { chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, ''); }
+       if (chunk) {
+         if (chunk == "\x7f" && input.length > 0) {
+           if (options.mask != '') { fs.writeSync(fdW, "\b\x1b[0K"); }
+           input = input.slice(0, -1);
+         }
+         chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '');
+       }
      if (chunk && limit) { chunk = chunk.replace(limit, ''); }

      if (chunk) {
```

**Comment by rksdevs** [comment]
> @rksdevs, I'm happy to help.
> **Please be sure to give more information next time, such as OS, Node version and code snippet from your actual app as well as the patched readline-sync.js!**
> 
> Here is a working patch I just tested and **confirmed it works on Linux**:
> 
> ```diff
>       if (chunk && typeof (line = (chunk.match(/^(.*?)[\r\n]/) || [])[1]) === 'string') {
>         chunk = line;
>         atEol = true;
>       }
> 
>       // other ctrl-chars
>       // eslint-disable-next-line no-control-regex
> -       if (chunk) { chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, ''); }
> +       if (chunk) {
> +         if (chunk == "\x7f" && input.length > 0) {
> +           if (options.mask != '') { fs.writeSync(fdW, "\b\x1b[0K"); }
> +           input = input.slice(0, -1);
> +         }
> +         chunk = chunk.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '');
> +       }
>       if (chunk && limit) { chunk = chunk.replace(limit, ''); }
> 
>       if (chunk) {
> ```
> 
> Sample usage code:
> 
> ```
> readlineSync = require('readline-sync');
> 
> var favFood = readlineSync.question('What is your favorite food? ', {
>   hideEchoBack: true
> });
> console.log('Yum: ' + favFood);
> ```

Thanks so much @markostamcar - it's working! 
I was patching the code snippet, incorrectly earlier, but with your recent help I was able to patch it correct and now it works exactly as intended! 
I've also noted the feedback, going forward while responding, will put all the relevant details to get help! I'm following your git profile! Thanks much!
