### ISSUE TITLE
Don't work properly with iojs v2.3.2+

### ISSUE THREAD

**Issue by seiya-git** [anseki/readline-sync#18]
Don't work properly with iojs v2.3.2+.
When run it's make two request from user (only when use function first time?):
With text ask, but ignored input parameters.
Without text ask, but don't ignore parameters.

Test case from sample.
```javascript
var readlineSync = require('readline-sync');

// Wait for user's response.
var userName = readlineSync.question('May I have your name? :');
console.log('Hi ' + userName + '!');

// Handle the secret text (e.g. password).
var favFood = readlineSync.question('What is your favorite food? :', {
  hideEchoBack: true // The typed text on screen is hidden by `*` (default).
});
console.log('Oh, ' + userName + ' loves ' + favFood + '!');
```
![Screenshot](http://ipic.su/img/img7/fs/kiss_2kb.1440246691.png)

**Comment by anseki** [comment]
Hi seiya-git, thank you for your report.
v2.3.2+ seems to have bugs about stream yet.
I made readlineSync avoid using it.
Could you check new readlineSync?

**Comment by seiya-git** [comment]
@anseki, thank you, everything seems to be working fine.
![Screenshot](http://ipic.su/img/img7/fs/kiss_39kb.1440337338.png)

**Comment by anseki** [comment]
Thank you for checking :smiley:
