### ISSUE TITLE
ANSI escape codes show up in output when pressing arrow keys, e.g., ^[[A^[[B^[[C^[[D

### ISSUE THREAD

**Issue by specious** [anseki/readline-sync#22]
[ANSI escape codes](http://unix.stackexchange.com/questions/222901/caret-square-bracket-square-bracket-a-a-what-does-it-mean) (e.g., `^[[A^[[B^[[C^[[D`) show up in the output when user input is being acquired using `readline-sync@1.2.21`

Here's a screenshot of the behavior when using `bitly-client@1.0.1`, where the sequence "up, down, right, left" was recorded as an input of `"[A[B[C[D"`:

![ANSI escape codes in bitly-client@1.0.1](https://cloud.githubusercontent.com/assets/451178/10207410/0d2eee1a-679a-11e5-8717-012fa6354df1.png)

Here's a test script that exhibits the behavior:

```
console.log('You typed: ' + require('readline-sync').question('Type here: '));
```

Expected behavior I think is for left and right keys to move the caret and up/down arrows to flip through the input history (if enabled).  I tested in several terminal emulators on OS X 10.9 with the same results.

**Comment by anseki** [comment]
Hi specious, thanks for your post.

readlineSync deliberately ignore the keys that control something. (e.g. arrow, backspace, home, etc.)
Some platforms (and environments) don't support the ANSI escape sequence. For example, Windows that is non-POSIX without `ansi.sys`.
Some samples in [README](https://github.com/anseki/readline-sync) use the ANSI escape sequence, those are parsed by Node or another library. (But some samples might not work fine in some environments.)

And current Node doesn't support controlling the readline system library (e.g. like the bash). `stty` and emulation editable readline are needed (system calling or native add-on). And it has problems in Windows.
readlineSync will not support controlling keys until Node supports those. And it's not used to non-CLI such as ncurses for TUI.

I think that, if you want to let your program run in many environments, you should not use the ANSI escape sequence, or you should consider some measures such as [chalk
](https://github.com/chalk/chalk) that recommend [cmder](http://cmder.net/).

**Comment by anseki** [comment]
There is no reply, and I close this issue.
If not solved, please reopen it.

**Comment by specious** [comment]
@anseki, I don't quite follow what you're saying.  

For `bitly-client`, I switched to using the much simpler [read](https://github.com/isaacs/read) module, which handles arrow keys intuitively and doesn't print escape codes.

**Comment by anseki** [comment]
As I said, that behavior differs depending on the environment. That is, it calls the readline system library such as GNU readline.

For example, your sample code in Win 8.1 + Node v4.2.1 or Node v0.12.6:

```js
console.log('You typed: ' + require('readline-sync').question('Type here: '));
```

First, I typed the text only, 2 times.
![01](https://cloud.githubusercontent.com/assets/4763469/10557608/a8e3da94-74ee-11e5-8db1-0127116e8599.png)

And then, I pushed the `UP`, `DOWN`, `RIGHT`, `LEFT` keys. I didn't type character.
![02](https://cloud.githubusercontent.com/assets/4763469/10557609/bc696a52-74ee-11e5-9d0b-b29746883c03.png)

1. When `UP` key was pushed, `bar` that is last typed text (i.e. history) was shown.
2. When `DOWN` key was pushed, nothing changed. (no text at next of `bar` in history.)
3. When `RIGHT` key was pushed, nothing changed. The cursor already positioned at right side of `bar`.
4. When `LEFT` key was pushed, the cursor moved to left.

And then, I pushed the `UP` key again, and `foo` was shown.

If you want to let the user use arrow keys in many environments, you should test it in each environments.

---
The "read" module is wrapper of [Readline](https://nodejs.org/api/readline.html) that is core module.
Remember, readlineSync is "Synchronous Readline". If you don't need "Synchronous", you don't need readlineSync.
And you need no module such as "read" module, if you want to just read text.

For example:

```js
var readline = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});

readline.question('Type here: ', function(answer) {
  console.log('You typed: ', answer);
  readline.close();
});

```

**Comment by anseki** [comment]
Of course, I will update readlineSync when those keys be controllable.

**Comment by specious** [comment]
@anseki, thank you for your reply, and I appreciate the suggestion to just use readline if that's all I need.

I just [switched](https://github.com/specious/bitly-client/blob/v2.0.0/index.js#L172-L186) to using native readline with `await` so the code flow remains linear.

I originally thought that readline-sync was just an easy way to use readline without needing a callback. Now I took a closer look and realised it doesn't use readline at all and reads stdin directly. So, I take it the point of using readline-sync is to be able to read keyboard input without the calling function having to become asynchronous.

For what it's worth, I just tested the latest readline-sync 1.4.10 in my terminal on a linux system, and it still doesn't let me edit the line and instead prints these same control characters. In other words, it prints control characters instead of moving the cursor on my system.

However, if I run the application with [rlwrap](https://github.com/hanslub42/rlwrap), then the line becomes editable.

**Comment by anseki** [comment]
Hi @specious, thank you for the comment.
I think that the readlineSync is not required now since we can write asynchronous code easily by `await`, etc.

**Comment by specious** [comment]
One would think, but what if you've got a synchronous function that other modules depend on (for example `getPassword()`) and it used to read the password from a file using `fs.readFileSync()`. And now you want to modify it to ask the user for the password. If you use an async function to do that, then your function will become async too, and all the modules will have to be updated to call it like an async function. Asynchronicity has this cascading effect.

As I understand, in some cases an API update may seem too bothersome.

**Comment by anseki** [comment]
Yes I know that the module is rather used for Utility Methods.
