### ISSUE TITLE
The platform doesn't support interactive reading

### ISSUE THREAD

**Issue by evilebottnawi** [anseki/readline-sync#26]
I use gitlab-ci and run in docker container debian:jessie from offical repo

**Comment by anseki** [comment]
Hi evilebottnawi, thank you for your report.

So, how did you use readlineSync? GitLab CI runner, build script for something, testing your app, or in your app?
If you tried to make readlineSync run in some wrapped environment such as CI auto script that runs at background (i.e. without TTY), readlineSync should not work, because readlineSync is used to reading that interactivity.

**Comment by evilebottnawi** [comment]
@anseki maybe not throw Exception, simply display an error and when you try use function also display error. Exception breaks build :(

**Comment by anseki** [comment]
So, how did you use readlineSync?

**Comment by evilebottnawi** [comment]
@anseki i use gulp and require readline-sync in gulp file

**Comment by anseki** [comment]
I see.
Try to execute `gulp` command directly with that gulpfile, then does it work fine?

**Comment by evilebottnawi** [comment]
@anseki yes all working fine outside docker container

**Comment by anseki** [comment]
TTY might have been not enabled.
Try to make docker run with `-t` option.
And make gulp run in this session.

**Comment by evilebottnawi** [comment]
@anseki https://gitlab.com/gitlab-org/gitlab-ci-multi-runner
no option for set -t

**Comment by anseki** [comment]
Not GitLab CI.
This is TTY test.

**Comment by evilebottnawi** [comment]
@anseki 
i run `ls -l /dev` 
output:
...
`crw-rw-rw- 1 root root  5,   0 Jan 15 16:43 tty`
...

tty exist in folder

**Comment by evilebottnawi** [comment]
@anseki full error from logs
```
stty: when specifying an output style, modes may not be set
/tmp/wordpress/src/wp-content/themes/insteria/node_modules/readline-sync/lib/read.sh: 49: /tmp/wordpress/src/wp-content/themes/insteria/node_modules/readline-sync/lib/read.sh: cannot create /dev/tty: No such device or address
stty: standard input: Inappropriate ioctl for device
/tmp/wordpress/src/wp-content/themes/insteria/node_modules/readline-sync/lib/readline-sync.js:66
    if (res.error) { throw res.error; }
                     ^

Error: The platform doesn't support interactive reading
stty: when specifying an output style, modes may not be set
/tmp/wordpress/src/wp-content/themes/insteria/node_modules/readline-sync/lib/read.sh: 49: /tmp/wordpress/src/wp-content/themes/insteria/node_modules/readline-sync/lib/read.sh: cannot create /dev/tty: No such device or address
stty: standard input: Inappropriate ioctl for device
```

**Comment by anseki** [comment]
Not existing test.
TTY has to enabled.

**Comment by anseki** [comment]
I don't know what you want to do, but if you don't need interactive reading, you can avoid the error by catching the thrown error.

```js
try {
  key = readlineSync.keyIn();
} catch (e) {}
```

**Comment by evilebottnawi** [comment]
@anseki with `-t` work all fine

**Comment by anseki** [comment]
Good for you :smiley:
So, was the issue solved? will this issue be closed?

**Comment by evilebottnawi** [comment]
@anseki no :(. gitlab-ci run without flag `-t`. But this is a problem not apply here.

**Comment by anseki** [comment]
You can enable TTY by `-t` option and specify `--name gitlab-ci-runner` to make it run within same session.
BTW, I don't know what you want to do... Why you need interactive reading in CI? These should be in conflict.
I think that you should catch the thrown error.

**Comment by anseki** [comment]
I think that this https://github.com/anseki/readline-sync/issues/26#issuecomment-172016932 might help you.

**Comment by evilebottnawi** [comment]
@anseki I searched through the documentation but could not find the option set up `-t`

**Comment by anseki** [comment]
I think that this https://github.com/anseki/readline-sync/issues/26#issuecomment-172016932 and this https://github.com/anseki/readline-sync/issues/26#issuecomment-172054121 might help you without `-t` option.

**Comment by evilebottnawi** [comment]
@anseki no

**Comment by SelimIkkache** [comment]
I'm using readline-sync on windows (git-bash.exe).
`C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:250
    if (res.error) { throw res.error; }
                     ^

Error: The current environment doesn't support interactive reading from TTY.
    at readlineExt (C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:212:19)
    at tryExt (C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:249:15)
    at C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:352:15
    at _readlineSync (C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:422:5)
    at getValidLine (C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:752:11)
    at Object.exports.question (C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\node_modules\readline-sync\lib\readline-sync.js:834:10)
    at Object.<anonymous> (C:\Users\sikkache\AppData\Roaming\npm\node_modules\jira\index.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

sikkache@DAP-CHA-POR0109 MINGW64 /d/Documents/Programmation/NodeJS/jira (master)
$ ^C

sikkache@DAP-CHA-POR0109 MINGW64 /d/Documents/Programmation/NodeJS/jira (master)
$ ls -l /dev
...
crw-rw-rw- 1 sikkache 1049089   5,   0 avr.   4 10:39 tty
`

Merci de votre aide

**Comment by anseki** [comment]
Hi @SelimIkkache,

Could you show me your code?
And, which version of  readlineSync, Windows, bash and Node.js?
Also, did the code work in CMD?

**Comment by SelimIkkache** [comment]
readline-sync@1.4.7
Windows: 7 
Git Bash: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
Node js: v6.9.5

```
#!/usr/bin/env node
// Entry point for the program
var readlineSync = require('readline-sync');
var Basic = require('./helper/basic')
var jiraLPCArgs = new (require('./helper/cli-args'))()

// Get password for JIRA
jiraLPCArgs.auth.setDigest(jiraLPCArgs.user,
  readlineSync.question('Enter your password ', {hideEchoBack: true}))
```

**Comment by SelimIkkache** [comment]
I closed my git bash and relaunch it, I have no more issues

**Comment by SelimIkkache** [comment]
By the way, this code works in CMD, but not in GitBash. 
There is no output at all on gitbash.

**Comment by anseki** [comment]
I see.
It seems that your environment (MinGW) does not support interactive reading from TTY. That is, the error message is correct.
Since readlineSync is library to read and write via TTY, of course it can't work with no TTY.

REPL also may not work in your environment. try this:
```
node
console.log('foo');
```

**Comment by SelimIkkache** [comment]
You're right, it doesn't work ever. 

So Howcan I make it work ?

**Comment by anseki** [comment]
That is solved simply, by using it in an environment that TTY is available.
I think that you probably use a decent terminal such as [Cmder](http://cmder.net/) instead of CMD that has many problems, as everyone knows.
Or, if you really want to use MinGW, https://github.com/anseki/readline-sync/issues/33 might help you. But I don't recommend it.

**Comment by SelimIkkache** [comment]
Thank you, you can solve the issue according to me.

**Comment by anseki** [comment]
😄
