### ISSUE TITLE
Backspace does not delete characters when hideEchoBack is true

### ISSUE THREAD

**Issue by wcspcbmt** [anseki/readline-sync#27]
OS: Mac OS X Yosemite (10.10.5)
NodeJS: 5.2.0 installed with homebrew
readline-sync: 1.2.22

var rl = require('readline-sync');
console.log(rl.question("Enter password: ", {hideEchoBack: true}));

Enter some text (123456) and hit backspace a couple times. No mask characters are erased (*) and the result is still 123456.

**Comment by anseki** [comment]
Hi wcspcbmt, thank you for your post.

You may use bash.
[This](https://github.com/anseki/readline-sync/issues/17) will help you.

**Comment by anseki** [comment]
There is no reply, and I close this issue.
If not solved, please reopen it.
