### ISSUE TITLE
feature request: Customizing text show for "CANCEL" option in list shown by keyInSelect

### ISSUE THREAD

**Issue by michael-fei** [anseki/readline-sync#28]
Currently, the keyInSelect function displays a list of options for the user to choose from and an optional additional option labeled "CANCEL". While I know that you can enable and disable showing the "CANCEL" option, I'd like to see an option to customize the text displayed for that additional option to something other than "CANCEL". Currently, the way I'm using the readline-sync keyInSelect function is that I'm displaying a list of options that the user can toggle on and off. Every time the user selects a menu option the state of that option is toggled and the menu is re-displayed, allowing the user to toggle other options. Once the user is done toggling the options they want to choose, then they press "0" to select the "CANCEL" option, which commits their selected options and continues the program. It works very well for my use case, except for the fact that the word "CANCEL" is very confusing to users. For my program, I'd like to be able to change the word "CANCEL" to something like "DONE", or "CONFIRM". The actual functionality would be exactly the same as it is now, I just want to be able to override the default text of "CANCEL" to something else. Is it possible for you to add this feature?

@anseki

**Comment by anseki** [comment]
Hi michael-fei, thank you for your suggestion.
I agree it, and I will update readlineSync soon.

**Comment by anseki** [comment]
[Done](https://github.com/anseki/readline-sync#cancel)

**Comment by michael-fei** [comment]
Thanks. I really appreciate your fast response time to adding this feature!
