### ISSUE TITLE
The platform doesn't support interactive reading

### ISSUE THREAD

**Issue by Darker** [anseki/readline-sync#31]
I get this error on windows 7x64.

**Comment by anseki** [comment]
Hi @Darker, thank you for your report.
That is valid behavior. The designed error is thrown deliberately, as its message say.

**Comment by Darker** [comment]
I don't nderstand. Does that mean Windows isn't supported?

**Comment by anseki** [comment]
Of course Windows is supported. It is not the cause.
In your case, you might have tried to make readlineSync run in environment that's disabled TTY.
So, how did you use readlineSync? Could you show me your code?
