### ISSUE TITLE
Backspace does not delete characters with hideEchoBack enabled

### ISSUE THREAD

**Issue by sant123** [anseki/readline-sync#35]
Hi, according with these closed issues https://github.com/anseki/readline-sync/issues/27 https://github.com/anseki/readline-sync/issues/17 I'd say this issue persist, and maybe the explanation of the #17 is right, but if it does; why we would erase the normal content (not hidden) with the backspace key? And if we are planning to change a password, what happens if I make a mistake? Do I have to repeat the whole process? Take this as an example:
* Please provide your current password: ******
* Provide a new password: ****x** "I've made a mistake!, and then the program will accept this password as my new password"
* Repeat your new password: ****x** "I have to do it in order to continue and then repeat the process"
* Start over!

I think this module is really awesome because in some way, I remember the C#  ```Console.ReadLine() ``` I'll appreciate this issue gets solved.

Thanks.

**Comment by anseki** [comment]
Duplicate issue was moved to https://github.com/anseki/readline-sync/issues/17#issuecomment-216591524
