### ISSUE TITLE
Make CANCEL option optional?

### ISSUE THREAD

**Issue by JoshMcCullough** [anseki/readline-sync#39]
When using `keyInSelect`, is it possible to remove the CANCEL option entirely?

**Comment by anseki** [comment]
Hi @JoshMcCullough,

You can disable it by specifying `false` to [`cancel`](https://github.com/anseki/readline-sync#cancel) option.

**Comment by JoshMcCullough** [comment]
Sorry, I missed that in the docs. Thanks!
