### ISSUE TITLE
Allow user to kill process during call to keyInYN/keyInYNStrict

### ISSUE THREAD

**Issue by trevorhreed** [anseki/readline-sync#42]
I am unable to kill the process (by pressing Ctrl+C or Ctrl+Z) when inside a call to either `keyInYN` or `keyInYNStrict`. Regular question calls work as expected, but I would think you would also want to let the user kill the process even in a call to `keyInYNStrict`. Or perhaps, this could be an option at least?

**Comment by anseki** [comment]
Hi @trevorhreed, thank you for the report.

If you are using Windows, try `Break key` (`Ctrl`+`Pause-Break`).

This may help you: https://github.com/anseki/readline-sync/issues/7

Node.js seems to do different behavior about handling `SIGINT` while TTY in raw mode, in some environments, shells, versions, etc.
It has been discussed at times (e.g. https://github.com/nodejs/node/issues/4758, https://github.com/nodejs/node/issues/3328, https://github.com/nodejs/node/issues/6626).
Someday, Node.js might solve this problem.

Now, better way I think is giving the choice to cancel to user without `^C`.
For example, [keyInPause](https://github.com/anseki/readline-sync#utility_methods-keyinpause) method allow user to make the final decision on whether something should do or not, after inputting all information.

**Comment by trevorhreed** [comment]
That's too bad. I will add a confirmation screen at the end to work around this. Really great library, by the way! Thanks!

**Comment by anseki** [comment]
:smiley:
