### ISSUE TITLE
how could it support chinese?

### ISSUE THREAD

**Issue by qinyadong** [anseki/readline-sync#43]

**Comment by qinyadong** [comment]
now the chinese text will be messy.

**Comment by anseki** [comment]
Hi @qinyadong,

Chinese is supported by ECMAScript (Node.js), with Unicode.
Can you express a concrete example?

**Comment by qinyadong** [comment]
In commandline,the inputstream's encoding is gbk ,gbk is not supported by nodejs, so wecan use the npm package of  iconv-lite. I hava rewrite someting so that it can support chinese

**Comment by qinyadong** [comment]
I make a new pull request. could you publish a new version to npm.org?

**Comment by anseki** [comment]
I see.
I think that this is not issue of readlineSync, and you need only a terminal that supports unicode.
For example, Node.js can do `console.log('你好')`, and readlineSync also display that.
Or, you can pass the converted string by `iconv` to that.

**Comment by anseki** [comment]
No reply came, and I close this issue.
