### ISSUE TITLE
keyInSelect has a limit of 35 array elements

### ISSUE THREAD

**Issue by smks** [anseki/readline-sync#47]
I have to display a huge list of directories so that the user can choose from one of them. What is the reason for the limit of 35?

**Comment by anseki** [comment]
Hi @smks, thank you for the comment.

- For the user, the list should not be too long. The size of many terminal windows is small, then your app should have a pagination (like `more` command) to show the long list.
- `keyInSelect` is used for simple interface. `0` .. `9`, `A` .. `Z` keys are found easily by user.
- The keys other than the 36 keys (includes `0`) are not many, if you want to receive multiple keys such as the item number for long list, you can use `questionInt` method. But I think that it's not good idea as I said. The list should be split. For example: https://github.com/anseki/readline-sync#itemscount

**Comment by smks** [comment]
I decided to use a columnify npm package, and built 4 columns of options to format and compact it a bit better. I then use a questionInt to grab the index. Great package by the way!

**Comment by anseki** [comment]
😃
