### ISSUE TITLE
file redirection not work ?

### ISSUE THREAD

**Issue by flowmemo** [anseki/readline-sync#57]
Hi, I am not sure if I miss something but I failed to make the official example run when using file redirection. 

There are two file:
main.js
```javascript
// official example
var readlineSync = require('readline-sync');

// Wait for user's response.
var userName = readlineSync.question('May I have your name? ');
console.log('Hi ' + userName + '!');

// Handle the secret text (e.g. password).
var favFood = readlineSync.question('What is your favorite food? ', {
  hideEchoBack: true // The typed text on screen is hidden by `*` (default).
});
console.log('Oh, ' + userName + ' loves ' + favFood + '!');
```

input.txt
```
CookieMonster
tofu

```

After running command `node main.js < input.txt`, the prompt seems to hang on the first question.

Thanks!

**Comment by anseki** [comment]
Hi @flowmemo, thank you for the comment.

So, do you mean that you can't type something?
Also, could you tell me your environment?

**Comment by flowmemo** [comment]
@anseki 
My expected behavior of `node main.js < input.txt` is same as running `node main.js` and then manually type the content of input.txt in the terminal.

I test this in macOS 10.12.6 and Ubuntu 16.04 with node 6.10.2 and the latest `readline-sync`.

**Comment by anseki** [comment]
I see.
It seems that you misunderstood readlineSync as a library to read from the standard input. It reads user input via TTY.
See the first part of the document. https://github.com/anseki/readline-sync
readlineSync deliberately try to read via TTY even if something is redirected.

**Comment by anseki** [comment]
You can read `input.txt` via `process.stdin`.

**Comment by flowmemo** [comment]
> readlineSync tries to let your script have a conversation with the user via a console, even when the input/output stream is redirected like your-script <foo.dat >bar.log.

Oh 😂! My fault. I totally misunderstood this part.

What should I do to achieve my goal?  I just want to find a synchronous version of node's readline.

Thanks!

**Comment by anseki** [comment]
You can use `fs.readSync` (or `readFileSync`) for the stdin.
