### ISSUE TITLE
Support for foreign characters

### ISSUE THREAD

**Issue by zrrtcs** [anseki/readline-sync#58]
Hi,
It seems that readline-sync does not support foreign characters.

Example: 
```
var answer = require('readline-sync').question("Enter thy answer: ")
console.log(answer)
```
All the input below will produce question marks character:
a. الدجاج والأرز
b. 鸡饭
c. אורז עוף

**Comment by anseki** [comment]
Hi @zrrtcs, thank you for the report.

ECMAScript (Node.JS) already supports Unicode, by default.
If your environment (not readlineSync) does not support those characters, the `console.log` method in your code can not print those when the `answer` contains those characters.

For example, CJK characters were shown correctly, in my environment.

``` js
const readlineSync = require('readline-sync');

console.log('ANSWER: ' + readlineSync.question('你好: '));
console.log('ANSWER: ' + readlineSync.question('こんにちは: '));
console.log('ANSWER: ' + readlineSync.question('안녕하세요: '));
```

Result:

```
你好: hello
ANSWER: hello
こんにちは: hello
ANSWER: hello
안녕하세요: hello
ANSWER: hello
```

So, confirm that your environment (terminal) supports those characters.
And these might help you:
https://github.com/anseki/readline-sync/issues/48
https://github.com/anseki/readline-sync/issues/54
https://github.com/anseki/readline-sync/issues/43

**Comment by zrrtcs** [comment]
omg, how could i missed through those repeated issues... 😳
yerp. just needed to configure my cmder.
thank you @anseki for the pointers.

**Comment by anseki** [comment]
😄
