### ISSUE TITLE
keyInSelect uses letters - why?

### ISSUE THREAD

**Issue by smks** [anseki/readline-sync#59]
keyInSelect starts using letters, but later on in the script when I need to get the index of the array, 'a', 'b' and 'c' etc. will break. It should just go from 1-999 and so on. There is also a random max array limit of 35 for some reason.

**Comment by anseki** [comment]
Hi @smks, thank you for the comment.

The `keyInSelect` method returns a number as an index of the `items` Array, it is a value you want. The method never returns `A`, `B`, `C`, etc.

See: https://github.com/anseki/readline-sync#utility_methods-keyinselect

**Comment by smks** [comment]
```javascript
const readLineSync = require('readline-sync');

const index = readLineSync.keyInSelect([
    'option 1',
    'option 2',
    'option 3',
    'option 4',
    'option 5',
    'option 6',
    'option 7',
    'option 8',
    'option 9',
    'option 10',
    'option 11',
    'option 12',
    'option 13',
    'option 14',
    'option 15',
    'option 16',
    'option 17',
    'option 18',
    'option 19',
    'option 20',
    'option 21',
    'option 22',
    'option 23',
    'option 24',
    'option 25',
    'option 26',
    'option 27',
    'option 28',
    'option 29',
    'option 30',
    'option 31',
    'option 32',
    'option 33',
    'option 34',
    'option 35',
]);

console.log('you chose ' + index);
```
Result:
```
node read-in-test.js

[1] option 1
[2] option 2
[3] option 3
[4] option 4
[5] option 5
[6] option 6
[7] option 7
[8] option 8
[9] option 9
[a] option 10
[b] option 11
[c] option 12
[d] option 13
[e] option 14
[f] option 15
[g] option 16
[h] option 17
[i] option 18
[j] option 19
[k] option 20
[l] option 21
[m] option 22
[n] option 23
[o] option 24
[p] option 25
[q] option 26
[r] option 27
[s] option 28
[t] option 29
[u] option 30
[v] option 31
[w] option 32
[x] option 33
[y] option 34
[z] option 35
[0] CANCEL

Choose one from list [1...9, a...z, 0]:
```

**Comment by anseki** [comment]
Yes, did you understand? 😄 
Please close this issue if it was solved.

**Comment by smks** [comment]
Can we increase the limit so it is not max of 35?

**Comment by anseki** [comment]
You saw the result of this line:

```js
console.log('you chose ' + index);
```

And you made sure that the returned value is the index of an Array.
For understanding that, your code might have to be this:

```js
const readLineSync = require('readline-sync'),
  items = ['option 1', 'option 2', 'option 3'],
  index = readLineSync.keyInSelect(items);
console.log('you chose ' + items[index]);
```

Maximum length is 35 for usability. That is, the user may not be able to find a key other than number and alphabet easily.
If you want to use more items, use Paging.
See this example:
https://github.com/anseki/readline-sync#itemscount

**Comment by tdelov** [comment]
I'm not sure I understand how to use Paging if I have an array greater than 35.

**Comment by anseki** [comment]
Hi @tdelov, thank you for the comment.
This is an issue about the return value of `keyInSelect` method.
And, unfortunately, no reply came from @smks. Surely @smks already understood that. I close this issue soon.
And also, you made [new issue](#60) about the "max 35", therefore we should use the new issue for that topic.
