### ISSUE TITLE
Can't set cancel option

### ISSUE THREAD

**Issue by martinp999** [anseki/readline-sync#64]
Cancel is not a property of BasicOptions, how do I specify a keyInSelect without a cancel option?

**Comment by anseki** [comment]
Hi @martinp999, thank you for the comment.
So, do you mean that you want to know how to use [`cancel`](https://github.com/anseki/readline-sync#cancel) option with [`keyInSelect`](https://github.com/anseki/readline-sync#keyinselect) method?

**Comment by martinp999** [comment]
When I do -
`readline.keyInSelect(items, query,{"cancel":false});`

I get 
> Argument of type '{ "cancel": boolean; }' is not assignable to parameter of type 'BasicOptions'.

`BasicOptions` looks like this - 

`export interface BasicOptions {
    prompt?: any;
    hideEchoBack?: boolean;
    mask?: string;
    limit?: OptionType | OptionType[];
    limitMessage?: string;
    defaultInput?: string;
    trueValue?: OptionType | OptionType[];
    falseValue?: OptionType | OptionType[];
    caseSensitive?: boolean;
    keepWhitespace?: boolean;
    encoding?: string;
    bufferSize?: number;
    print?(display: string, encoding: string): void;
    history?: boolean;
    cd?: boolean;
    charlist?: string;
    min?: any;
    max?: any;
    confirmMessage?: any;
    unmatchMessage?: any;
    exists?: any;
    isFile?: boolean;
    isDirectory?: boolean;
    validate?(path: string): boolean | string;
    create?: boolean;
    guide?: boolean;
}`

That is - there is no "Cancel" property.

Am I missing something?

**Comment by anseki** [comment]
Do you use the readlineSync in TypeScript?
It seems that you use TypeScript and wrong type definitions.
That is, this JS code works fine:
```js
const items = ['item-A', 'item-B', 'item-C'],
  index = require('readline-sync').keyInSelect(items, null, {cancel: false});
console.log(`INDEX: ${index}`);
```

**Comment by martinp999** [comment]
You're correct.  Apologies - I'm new to TypeScript.  I've done a PR to get this fixed https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23176

**Comment by anseki** [comment]
👍 😄
