### ISSUE TITLE
async/await in prompt

### ISSUE THREAD

**Issue by ardabeyazoglu** [anseki/readline-sync#65]
Hi,

Is there any way to run async function inside prompt commands ? The following does not work as expected. `data` is logged to console successfully, however the tool does not return to command prompt again. If i dont use async/await, it works normally.

```javascript
readlineSync.promptCLLoop({
        async add(){
            try {
                    let data = await myAsyncFunction();
                    console.log(data);
                }
                catch(ex){
                    console.error(ex);
                }
        }
    });
```

**Comment by anseki** [comment]
Hi @ardabeyazoglu, thank you for the comment.

An async function returns a `Promise`. And `promptCLLoop` method exits the loop when `commandHandler` returns a `true` such as a `Promise` that is truthy value.
https://github.com/anseki/readline-sync#promptclloop

The purpose of async/await functions is to simplify the behavior of using **asynchronous** function. "readlineSync" is **synchronous** readline. You can use "readline" (not "readlineSync") for asynchronous behavior.

**Comment by anseki** [comment]
So, `data` is logged to console before it returns to command prompt again because `console.log` was written in the `add`.
If `data` is logged before `myAsyncFunction` finishes, the `myAsyncFunction` seems to have a problem. e.g. `myAsyncFunction` calls `resolve`.

**Comment by ardabeyazoglu** [comment]
Thanks for the answer. I actually combined both libraries, now it works perfect.

**Comment by anseki** [comment]
😄
