### ISSUE TITLE
Readline-sync and mocha

### ISSUE THREAD

**Issue by JacekTchorzewski-CL** [anseki/readline-sync#67]
Hi,

First of all thanks for awesome library. 
Currently I'm writing small CMD program and I wanted to write some tests for it. My approach was to create child process in my tests and pass STDIN through `process.stdin.write` method. Unfortunately I run into some problems with that.

I will give code example to show what I want to achieve.

File `program.js`:
```javascript
var readlineSync = require('readline-sync');

console.log("Provide your name:")
var userName = readlineSync.prompt();
console.log("Hi " + userName);
```

And `test.js`:
```javascript
var childProcess = require('child_process');
var assert = require('assert');


it('tests', function(done) {
  var process = childProcess.fork("./program.js", [], {stdio: 'pipe'});
  
  process.stdout.once('data', (out) => {
    assert.equal(out.toString().trim(), 'Provide your name:');
    process.stdin.write('Jacek\r\n');
    process.stdout.once('data', (out) => {
      assert.equal(out.toString().trim(), 'Hi Jacek');
    });
  });
  
  process.on('exit', (code) => {
    done();
  });
});
```

After I rum mocha tests the prompt sign is displayed in console and tests times out. It looks like `prompt` method does not read text i send.

Do you know how to fix this? Or maybe this is not the best approach for testing `readline-sync`?

**Comment by anseki** [comment]
Hi @JacekTchorzewski-CL, thank you for the comment. :smile:

readlineSync tries to input and output via TTY even if that is redirected.
See: https://github.com/anseki/readline-sync
That is the TTY might be not STDIN/STDOUT. And your test code does that.

As you said, it seems that your test code is not typical way.
For example, your test code checks whether the readlineSync returns `Provide your name:` or not. However that is a test for readlineSync, not your program.
Your test code should check your program passes `Provide your name:` to readlineSync. In other words, the test should check the output of your program, it doesn't have to check the output of readlineSync.
Typically a tool such as [Sinon.js](http://sinonjs.org/) (spy, stub, mock) is used for cases like your case. You can test your program by using "stub" that simulates the readlineSync, and you can check the string that was passed by your program.

**Comment by JacekTchorzewski-CL** [comment]
@anseki Thanks for answering so fast. 

I will rethink my testing approach. For now I'm closing this issue.
