### ISSUE TITLE
The input(which is chinese) get from readline-sync is Garbled 

### ISSUE THREAD

**Issue by chenvan** [anseki/readline-sync#68]
```js
let title = readlineSync.question('岗位名称: ')
console.log(title)
```
I input a chinese name 烘丝, but the console result is garbled

the output screenshot show below:

![problen](https://user-images.githubusercontent.com/7885757/37886694-72e3331c-30ef-11e8-86b2-078741e1bdd8.png)

**Comment by anseki** [comment]
Hi @chenvan, thank you for the comment.
These may help you:
https://github.com/anseki/readline-sync/issues?q=is%3Aissue+chinese

**Comment by chenvan** [comment]
so quick reply :-)
Sorry, I should mention that I do read all the issue about Chinese at the beginning :-( . But I found nothing help

**Comment by anseki** [comment]
So, did you try the `chcp 65001`?

**Comment by chenvan** [comment]
yes, of course

**Comment by chenvan** [comment]
I find another cli module [prompts](https://github.com/terkelg/prompts), and it does not have this problem. 
Thanks all the same

**Comment by anseki** [comment]
:smile:
