### ISSUE TITLE
Eval'ing readline-sync return a Promise

### ISSUE THREAD

**Issue by Grimscythe1983** [anseki/readline-sync#69]
I am attempting to use `eval` with readline-sync, however the returned variable is a promise, not resolved.

Example non-eval'ed:
```ts
let foo;
foo = readlineSync.question('bar:');
console.log(foo); // contains whatever was inserted as anticipated
```

Example eval'ed:
```ts
let foo;
eval("foo = readlineSync.question('bar:')");
console.log(foo); // contains a promise, why?
```
Why is it a Promise? And if possible how can I resolve that promise inside the eval?

**Comment by Grimscythe1983** [comment]
I probably should have mentioned that I use typescript. Maybe that's at fault, although it shouldn't be, really.

**Comment by anseki** [comment]
I see.
So, please close this issue if it was already solved.

**Comment by Grimscythe1983** [comment]
I'll do some troubleshooting and I'll close the issue, once I'll figure out wherein lies the fault. Might be helpful for someone else.

**Comment by Grimscythe1983** [comment]
Must have been late. The wrapper function around `readlineSync` had an `async` from the previous version of the function, and thus it was returning a promise. Sorry for the hassle and thank you for the swift answer.

**Comment by anseki** [comment]
Thank you for the report :smile:
