### ISSUE TITLE
Help about .question s

### ISSUE THREAD

**Issue by elmort16** [anseki/readline-sync#70]
Hey! Iam using readline-sync with node-steam-user but i need help about question types.
I used `readlineSync.questionInt` and `readlineSync.questionFloat` basically i want to ask to user to type the games that he wants to hour boost but unfortunately when i add a space between game ids the readlineSync doesnt read after the white spaces i must get the input like `10, 70, 30, 300` but when i type as i wrote it reads as `10` but if i use `readlineSync.question` it reads as string and i dont want to get the input as string. I stuck on that problem and i couldnt find a solution yet. What kind of question should i use? Can you help me?

**Comment by elmort16** [comment]
Hour boost means boosting your recorded game hours in Steam and game id is the special id of a game. I couldnt describe correctly but the solution that you gave me is fixed my problem. Thank you a lot

**Comment by anseki** [comment]
:smile:
