### ISSUE TITLE
How to fix chinese character garbled ?

### ISSUE THREAD

**Issue by hong-boy** [anseki/readline-sync#71]
Hi,

Is there any appropriate way to fix it ?

OS: win8.1
Nodejs: v10.10.0

```
const readline = require("readline-sync");

readline.question("我是中文乱码, utf-8", {
    encoding: "utf-8"
});
```

![image](https://user-images.githubusercontent.com/28519731/45920117-9b236d80-bed2-11e8-961e-cc56d7a866e3.png)

**Comment by anseki** [comment]
Hi @hong-boy, thank you for the comment.
You don't have to specify the `encoding` option because the default value is `'utf8'` (Not `'utf-8'`).
And you have to save the script file with "UTF-8" encoding.

**Comment by hong-boy** [comment]
@anseki I removed "encoding" option, but the issue is still there :(

![image](https://user-images.githubusercontent.com/28519731/45923626-c2535c80-bf1d-11e8-9f9f-db455c918253.png)

**Comment by anseki** [comment]
You have to save the script file with "UTF-8" encoding.
I tried your code:

```
node ./test.js
我是中文乱码, utf-8
```

**Comment by hong-boy** [comment]
First thank you so much, and second sorry for the duplicated issue. #48 inspired me.

**Comment by anseki** [comment]
:smile:
