### ISSUE TITLE
Nodemon <<>> readline-sync

### ISSUE THREAD

**Issue by AsheAustaire** [anseki/readline-sync#73]
While running .js files with nodemon the input is not always accepted after the first enter keypress while using prompt or question methods.

Here is an example using nodemon. As you can see, the first enter keys do not trigger the next question.
<img width="626" alt="nodemon" src="https://user-images.githubusercontent.com/27021764/48725962-de146f80-ebfb-11e8-9c60-9a13b51f9b42.png">

Here is an example using Node where every key triggers the next prompt/question
<img width="601" alt="node" src="https://user-images.githubusercontent.com/27021764/48725955-d48b0780-ebfb-11e8-87d8-3e14ff79d13e.png">

**Comment by anseki** [comment]
Hi @AsheAustaire, thank you for the report.
Could you indicate the reproducing that such as example codes?

**Comment by anseki** [comment]
BTW, I fixed your strange bolded text. You maybe mistook format.

**Comment by anseki** [comment]
No reply came, then I close this issue.
