### ISSUE TITLE
Can't read Russian

### ISSUE THREAD

**Issue by nagayev2002** [anseki/readline-sync#76]
My code:
`var readline = require("readline-sync");
var q = readline.question("Hi> ");
console.log(q.codePointAt(0));`
Win10, NodeJS 11.4
Encoding is utf-8(65001). I entered ф and saw undefined.
Then I set encoding to 1251 and saw 65533
Same result with 866.
FIle encoding is utf-8(default encoding in Visual studio Code)

**Comment by anseki** [comment]
Hi @nagayev2002, thank you for the comment.
I tried your code, then that worked fine.
```
>node test
Hi> ф
1092 
```
It seems that your terminal does not support inputting that.

**Comment by nagayev2002** [comment]
@anseki I tryed on PowerShell and on cmd.
Did you try on Windows?

**Comment by anseki** [comment]
I tried that on Linux.
Ah, Windows, especially CMD has many problems.
If you want to use CMD, maybe you had better choose [`Readline`](https://nodejs.org/dist/latest-v10.x/docs/api/readline.html) or another module (e.g. [`prompts`](https://github.com/terkelg/prompts)).

**Comment by anseki** [comment]
Microsoft may update the CMD because it is well known that the CMD has many problems.

**Comment by nagayev2002** [comment]
@anseki ok
