### ISSUE TITLE
Readline Question overrides console logs

### ISSUE THREAD

**Issue by Vandesm14** [anseki/readline-sync#79]
When executing `readlineSync.question()`, it overrides any `console.log`'s that may happen asynchronously (the logs never go through to the console). Is there a way to allow the logs to pass through, but keep the question running?

**Comment by anseki** [comment]
Hi @Vandesm14, thank you for your comment.

So, do you mean that you want to abort the waiting for user's input when the `question()` is running?

**Comment by anseki** [comment]
You can abort the waiting for user's input when the `question()` (or another) is running, by using signals. For example, `SIGTERM` as the timeout for input.
readlineSync throw an error when it caught signal. An Error object that was thrown has `signal` property such as `'SIGTERM'`.

However, that is not good idea, and you should use "Readline" (not "readlineSync"). The "readlineSync" is a library for the synchronous running. I.e. that is inconsistent.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
