### ISSUE TITLE
Encoding Error, Portuguese Characters [ç ã] are not being displayed properly on the question. 

### ISSUE THREAD

**Issue by Werner1201** [anseki/readline-sync#80]
This problem is showing up when I execute the function, these characters get corrupted, I'm not well informed about encoding, but I suppose the default encoding 'utf8' should work fine with theses characters. This is the Code I was Trying to run. 

<pre>
const leia = require('readline-sync');

leia.setDefaultOptions({ encoding: 'utf8' });
function opcoes() {
  let resp = parseInt(leia.question("Qual operação você deseja?\n1:Inserção\n2:Remoção\n3:Busca\n4:Percorrer\nDigite: ", { encoding: 'UTF-8' }));
  return resp;
}
</pre>

I even tried using the setDefaultOptions from the Documentation, Although I did not have success.  
Is this a problem of Windows  CMD ? because I use it without any plugin.  I hope it's just a bad configuration option or if I just done goofed.

EDIT #1
![image](https://user-images.githubusercontent.com/8631657/59989909-68500680-9617-11e9-9f38-3ad4bdc59d06.png)
That's the result when executed.

**Comment by Werner1201** [comment]
I was doing somemore testing, when I print the same "query" line on console.log it shows up correctly. I dunno what's going on

**Comment by anseki** [comment]
Hi @Werner1201, thank you for your comment.
That seems a problem of the CMD.
These may help you:
https://github.com/anseki/readline-sync/issues?q=is%3Aissue+encoding

**Comment by Werner1201** [comment]
So, I saw a solution of using a console.log inside the question. how would I do to make the input prompt to not be one line down ?

**Comment by Werner1201** [comment]
Well, since the problem was Kinda Fixed by that, I think I'm done. Thanks for the Help, A I'm just waiting for your anwser on the previous commnent

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by Werner1201** [comment]
Yes, I could
