### ISSUE TITLE
Switch to cooked mode when readline-sync is called

### ISSUE THREAD

**Issue by amasad** [anseki/readline-sync#82]
If the terminal is in raw mode (for whatever reason) and readline-sync is called then it will not work properly (as it seems to rely on cooked mode). 

We can fix this by forcing cooked mode when a `readline-sync` method is called and then returning to the previous mode when `readline-sync` finishes execution?

Happy to try my hand at sending a PR for this... would you be open to it?

**Comment by anseki** [comment]
Hi @amasad, thank you for the report.
As you said, the current version of readlineSync doesn't check the raw mode of before the method running.
I will fix that when I have time.
Thank you for letting me know about that.

**Comment by anseki** [comment]
I tried to fix this issue but it seems not easy.
I couldn't find a way to definitely get the current mode.
Some properties don't work. `TTY#isRaw`, `TTY#owner.isRaw`, `TTY#ReadStream.isRaw`, etc.

So, I will defer this matter. And I welcome any information about this issue.
Thank you.

**Comment by anseki** [comment]
At the moment, I close this issue because the way to get the mode doesn't seem to exist.
And I still welcome any information about that.

Maybe, I think that this is not big problem because this is rare case and the person who changes the mode should understand the mode (i.e. can restore the mode).
