### ISSUE TITLE
sync with timeout

### ISSUE THREAD

**Issue by bjbarouch** [anseki/readline-sync#83]
Example: The user made a request that could not be fulfilled, but reasonably thought it would be. I'd like to ensure the user is made aware that it was not fulfilled, but on the other hand, I don't want to stop processing forever and possibly surpass the session timeout if the user has been interrupted by a conversation with a colleague, etc. So, as with other sync i/o functions, being able to specify a timeout, and getting a signal (or callback or whatever) when it ends via timeout instead of user action would be useful.

Example: I am waiting for a user reponse, and the session times out so I want to stop waiting and log out.

I see that this can be achieved with a child process, but that seems very heavyweight. Why not just use readline for these cases? Because then I cannot prevent other processing from spewing things to stdout between my rl.question and the user's reply.

Thoughts?

**Comment by anseki** [comment]
Hi @bjbarouch, thank you for the comment.
As you said, you can abort the waiting for user's input easily when the `question()` (or another) is running, by using signals.
However, that is not good idea, and you should use "Readline" (not "readlineSync"). The "readlineSync" is a library for the synchronous running. I.e. that is inconsistent.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
