### ISSUE TITLE
rlSync not reading accented characters

### ISSUE THREAD

**Issue by celynjacobs** [anseki/readline-sync#84]
Hello!

I am working on a project which uses rlSync to accept user input of a name and then performs various searches using the name. Currently, all goes well except for when a user inputs a name which uses accented, or non-ASCII characters. Does rlSync process those characters? I have created a test algorithm which suggests that it does not. When I type "Hëllo" in response to an rlSync prompt, it console.logs "Hllo", suggesting that it simply ignored the accented character.

I would appreciate any help y'all can provide! Thank you!

**Comment by anseki** [comment]
Hi @celynjacobs, thank you for your comment.
I couldn't understand this issue having no description. And this was already closed by you.
Did you mistake?

**Comment by celynjacobs** [comment]
Yeah don’t worry about it. I’m struggling with an encoding issue and I’m using readline-sync, but as you’ve pointed out to many others, readline-sync isn’t the problem. It’s Windows.

**Comment by anseki** [comment]
:smile:
