### ISSUE TITLE
Spanish characters: ñáéíóú¿

### ISSUE THREAD

**Issue by JuanFF** [anseki/readline-sync#86]
Hi,
In Mac's terminal, this is working, but when I run my script on Windows 10's console, Spanish characters aren't properly displayed:
a├▒o
a�o

```
const readlineSync = require('readline-sync');
userInput = readlineSync.question('Escribe la palabra "año": ');
console.log(userInput );
```

Please, can you help me to fix this?

Thanks!

**Comment by anseki** [comment]
Hi @JuanFF, thank you for your comment.
That seems a problem of the Windows CMD.
These may help you:
https://github.com/anseki/readline-sync/issues/48
https://github.com/anseki/readline-sync/issues?q=is%3Aissue+encoding

**Comment by JuanFF** [comment]
I tried the solution provided in #48 
I enter chcp 65001 on the console, but the result keeps failing
Instead of
a�o
Now it shows
ao

**Comment by anseki** [comment]
I tried your example code.
Then, it seems to be working fine.
```
Active code page: 65001

E:\tmp>node test1
Escribe la palabra "año": foo
foo

E:\tmp>
```
Did you try the code in your first comment?

**Comment by JuanFF** [comment]
The problem is on the input rather on display.
Instead of "foo", type "año". The "ñ" character can't be displayed

**Comment by JuanFF** [comment]
```
Escribe la palabra "año": año
ao
```

**Comment by anseki** [comment]
I see.
Maybe, that can't be readed via TTY in CMD.
See: https://github.com/anseki/readline-sync/issues/76

**Comment by JuanFF** [comment]
So I'm afraid that there's no solution for this

**Comment by anseki** [comment]
As I said in #76, the solution is fixed CMD.
Unfortunately, we can do nothing, for the problem of CMD.
Also, maybe you had better choose another module.

**Comment by JuanFF** [comment]
Thanks for your help, anyway.
This may work, instead:
https://www.npmjs.com/package/synchronous-user-input

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by JuanFF** [comment]
Sure

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
