### ISSUE TITLE
Can't delete Chinese characters

### ISSUE THREAD

**Issue by wznonstop** [anseki/readline-sync#87]
version: "readline-sync": "^1.4.10"
usage:
``` shell
const commitInfo = readlineSync.question('\n\033[44;37m请输入commit信息【必填】\033[44;5m: \033[0m ');
```

problem:
first, type "十九八七六五四三二一" like this:

![image](https://user-images.githubusercontent.com/9294582/64688792-a98ddf00-d4bf-11e9-9870-30e0ca4280c9.png)

then, try to delete all the characters:

![image](https://user-images.githubusercontent.com/9294582/64688822-bb6f8200-d4bf-11e9-81db-49b3a6e869cf.png)

here is the problem, I can't delete the left characters

is it a bug, can you help to fix it?
Best regards

**Comment by anseki** [comment]
Hi @wznonstop, thank you for your comment.
What is the "left characters"?
I tried your code, then I could delete the "十九八七六五四三二一" that were already input by using the key.
If the "left characters" means `query` argument that was passed to `question` method, that is correct behavior. Those should not be changed by user.

**Comment by wznonstop** [comment]
"十九八七六五四三二一"  is the `response`
![屏幕录制-2019-09-12-下午4 38 35](https://user-images.githubusercontent.com/9294582/65015641-b180cf80-d954-11e9-97b2-6dee12331754.gif)

**Comment by wznonstop** [comment]
That's exactly what I want! But it behaves differently on our computers. In fact, I didn't expect it to work properly on your computer, because it didn't work well in all my colleagues' computers🤦‍♀️

My computer version:
macOS Mojava 10.14.6

node version:
v11.12.0

**Comment by anseki** [comment]
Maybe, your terminal can't handle multibyte character set (variable-width encoding) correctly.
Or, the escape code like `\033[44;37m` might make problem in your terminal. Remove those as a test.

**Comment by wznonstop** [comment]
Maybe it's my terminal's problem, thanks for your reply😃

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
