### ISSUE TITLE
Chinese character problem, again

### ISSUE THREAD

**Issue by greymanking** [anseki/readline-sync#88]
I have a script, which uses readline-sync to get a file path. When the path contains Chinese characters, It does not work. I tried the chcp command, but it did not solve the problem.
for instance, when I input:

```
d:\百度云\我的影像\壁纸收藏\800065210.jpg
```
the console.log output is:

```
d:\\\\800065210.jpg
```
so node.js does not think this is a valid file path.
the problem occurs after I have changed the code page to 65001
any ideas?

**Comment by anseki** [comment]
Hi @greymanking, thank you for the comment.
Could you show me your code?

**Comment by greymanking** [comment]
My code is quite simple:

```
let path = readlineSync.question('please input the file path to upload:');
console.log(path);
if (fs.existsSync(path)) {
  console.log("file exists");
  let st = fs.lstatSync(path);
  if (!st.isDirectory()) {
    console.log("start uploading...");
    uploadFile(path);
  } else {
    console.log("directory can not be uploaded");
  }
} else {
  console.log("file does not exist");
}
```

**Comment by anseki** [comment]
I tried your code:
```
please input the file path to upload:d:\百度云\我的影像\壁纸收藏\800065210.jpg
d:\百度云\我的影像\壁纸收藏\800065210.jpg
file does not exist
```
Try another terminal instead of CMD if you are using CMD, or another library for prompt.

**Comment by greymanking** [comment]
This is really weird. I have tested the code on Windows 10 and 7, with cmd, powershell, bash, cmder, chcp & no chcp -- in one word, tried everything, but the problem is still there.
So, would you please tell me your node.js and readline-sync version?

**Comment by anseki** [comment]
Yes, of course this is a problem on only Windows.
As I said, you had better use another library for prompt instead because it is dependent on environment.

**Comment by greymanking** [comment]
OK, I will attempt to bypass this with another library. Anyway, thanks for your time and patience.

**Comment by anseki** [comment]
:smile:
