### ISSUE TITLE
Problems when running with nodemon

### ISSUE THREAD

**Issue by A1-exe** [anseki/readline-sync#90]
![image](https://user-images.githubusercontent.com/28128898/80815927-24f9e900-8b94-11ea-9e6d-9a1b54eb05c9.png)

This error appears when using nodemon, it does not happen when ran with the node command.

**Comment by anseki** [comment]
Hi @A1-exe, thank you for the comment.
Try `--no-stdin` option.
This option might help you, or it might not do that. readlineSync can work in only environment that supports TTY.
https://github.com/anseki/readline-sync

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
