### ISSUE TITLE
Other code cannot be run

### ISSUE THREAD

**Issue by OPS-LightOxygen** [anseki/readline-sync#91]
Hello,

I'm using this Node Module as a benefit for a DiscordJS client, and the other actions cannot be run while the prompt is activated.

How can I run the script **and** the readline in the same time?

I'm actually using promptCL like this:
```js
readlineSync.promptCLLoop({
    shutdown: () => {
        console.log("Shutdown the bot client.");
        process.exit(0);
    }
})

bot.login(config.token.discord); // Connection method from Discord
```

I don't think I'm the only one who have this kind of issue, it's why I've created a issue ticket.
Best regards,
LightOxygen

**Comment by anseki** [comment]
Hi @OPS-LightOxygen, thank you for the comment.

The `promptCLLoop` executes `promptCL` method repeatedly.
Therefore, the line including `bot.login...` is run after the `promptCLLoop` exited from the loop.
See document: https://github.com/anseki/readline-sync#promptclloop

I don't know what you want to do, but maybe your code should be like this:

```js
readlineSync.promptCLLoop({
  login() {
    bot.login(config.token.discord); // Connection method from Discord
    // Or, login before promptCLLoop
  }
  shutdown() { return true; }

  // Other commands...
  message(text) {
    message.reply(text);
  }
});

console.log('Shutdown the bot client.');
// Closing process...
```

**Comment by OPS-LightOxygen** [comment]
Hi, 

Thanks for your reply.

Have a nice day,

**Comment by anseki** [comment]
:smile:
