### ISSUE TITLE
"Assertion `(argc) == (5)' failed." error on calling functions

### ISSUE THREAD

**Issue by SupersonicXD1** [anseki/readline-sync#92]
I have been getting an error every time I run a readline-sync function. The error as is follows:

> C:\Program Files\nodejs\node.exe[3156]: c:\ws\src\node_file.cc:1550: Assertion `(argc) == (5)' failed.
 1: 000000013FA4D1EF napi_wrap+113103
 2: 000000013F9ECA66 v8::base::CPU::has_sse+64982
 3: 000000013F9ECDE1 v8::base::CPU::has_sse+65873
 4: 000000013F9DF961 v8::base::CPU::has_sse+11473
 5: 00000001401BD850 v8::internal::Builtins::builtin_handle+323456
 6: 00000001401BCD97 v8::internal::Builtins::builtin_handle+320711
 7: 00000001401BD0D8 v8::internal::Builtins::builtin_handle+321544
 8: 00000001401BCEDE v8::internal::Builtins::builtin_handle+321038
 9: 0000000140656D4D v8::internal::SetupIsolateDelegate::SetupHeap+546893
10: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
11: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
12: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
13: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
14: 00000001405D4F2C v8::internal::SetupIsolateDelegate::SetupHeap+14892
15: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
16: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
17: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
18: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
19: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
20: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
21: 00000001405DBBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
22: 00000001405D9131 v8::internal::SetupIsolateDelegate::SetupHeap+31793
23: 00000001405D8D1C v8::internal::SetupIsolateDelegate::SetupHeap+30748
24: 00000001401178A3 v8::internal::Execution::CallWasm+1395
25: 0000000140117226 v8::internal::Execution::Call+182
26: 00000001401E829D v8::Function::Call+605
27: 000000013FA1679E node::Start+1150
28: 000000013FA169D7 node::Start+1719
29: 000000013FA150BA node::LoadEnvironment+26
30: 000000013F9A479C v8::internal::interpreter::BytecodeArrayWriter::source_position_table_builder+31596
31: 000000013FA16433 node::Start+275
32: 000000013F886A9C RC4_options+340380
33: 000000014070ED38 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
34: 00000000771E556D BaseThreadInitThunk+13
35: 000000007744372D RtlUserThreadStart+29

I am on Windows 7, running node.js version 12.16.3 in Webstorm 2020.1.1. I am very new to node.js, so if I'm missing any information you need, I will provide it. Thanks in advance!

**Comment by anseki** [comment]
Hi @SupersonicXD1, thank you for the comment.
Could you explain to reproduce that?
In other words, what did you do? For example, the code? The command?

**Comment by SupersonicXD1** [comment]
@anseki The code:
`const readlineSync = require('readline-sync');
readlineSync.question("crash")`
Note that using `require()` does not crash node.js, but calling `readlineSync.question();` does.

**Comment by anseki** [comment]
Did you run that code in Windows CMD?

**Comment by a-hegerath** [comment]
FYI: I use to get this error when running a Javascript file from my IDE (in that case, IntelliJ IDEA), but when I run it in Windows CMD or Windows Powershell, the error does _not_ show up.

**Comment by anseki** [comment]
Hi @a-hegerath, thank you for the information.
Yes, as you said, I also guess that @SupersonicXD1 mistook the environment that runs the code.

**Comment by SupersonicXD1** [comment]
@anseki sorry for getting back to you so late, I've been busy for the past few days. I ran the code in the IDE (WebStorm), not windows command prompt.

**Comment by anseki** [comment]
I see.
That is correct behavior.
readlineSync is a library to read/write via TTY.
See document: https://github.com/anseki/readline-sync
Therefore, of course that should never work without TTY (i.e. an environment that has no TTY).

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
