### ISSUE TITLE
keypress event not firing after keyInSelect

### ISSUE THREAD

**Issue by Infrox** [anseki/readline-sync#96]
Hey,
In my app I need to detect all keypresses in the console.
This is the code to detect keypresses:
```
readline.emitKeypressEvents(process.stdin);
process.stdin.setRawMode(true);
process.stdin.on('keypress',(key,data)=>{
	console.log(key,data);
});
```

at some point I use `readlineSync.keyInSelect(["Option 1","Option  2"],"Select:",{cancel:false,encoding:"utf8"});`
after that, the keypress event is not firing anything. Is readline-sync somehow locking up the process.stdin?

**Comment by Infrox** [comment]
Solved this myself, I had to do `process.stdin.resume()`.

**Comment by anseki** [comment]
:smile:
